# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesource',
            options={'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90', 'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90'},
        ),
        migrations.AddField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('qd', '\u524d\u6bb5'), ('hd', '\u540e\u7aef'), ('ydd', '\u79fb\u52a8\u7aef')], default='ydd', max_length=5, verbose_name='\u7c7b\u522b'),
        ),
    ]
