# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(max_length=50, verbose_name='\u7528\u6237\u6635\u79f0'),
        ),
    ]
