# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('homeBanner', '\u9996\u9875banner\u56fe'), ('modelBanner', '\u9996\u9875modelBanner\u56fe')], default='homeBanner', max_length=15, verbose_name='banner\u56fe\u7c7b\u578b'),
        ),
    ]
