# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170523_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u5fd8\u8bb0\u5bc6\u7801'), ('change', '\u4fee\u6539\u90ae\u7bb1')], default='register', max_length=10),
        ),
    ]
